name: Billiamville
favicon: null
layout_spectrum: 0.22197
typography_spectrum: 0.63362
title: Billiamville - The collective website of everybody named Billiam Coronel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ffec'
    - '#11110f'
    - '#ea2829'
    - '#7b5e5a'
    - '#d98f82'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
