name: Billiamville
favicon: null
layout_spectrum: 0.22197
typography_spectrum: 0.63362
title: Billiamville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#87b0d0'
    - '#8a765e'
    - '#6a5848'
    - '#2e2a15'
    - '#ac9464'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
